### ISSUE TITLE
rat-pac-jsns2 compile error on os x

### ISSUE THREAD

**Issue by hephys** [rat-pac/rat-pac#59]
- Working on OS X with root5.34.36/Geant4.10.01.03 
- after coning and scons, terminal shows messages as below:

src/physics/PhysicsList.cc:162:3: error: instantiation of variable
      'G4VUPLSplitter<G4VUPLData>::offset' required here, but no definition is
      available [-Werror,-Wundefined-var-template]
  theParticleIterator->reset();
  ^
/opt/geant4/bin/../include/Geant4/G4VUserPhysicsList.hh:153:56: note: expanded
      from macro 'theParticleIterator'
#define theParticleIterator ((this->subInstanceManager.offset[this->g4vu...
                                                       ^
/opt/geant4/bin/../include/Geant4/G4VUPLSplitter.hh:195:38: note: forward
      declaration of template entity is here
    G4RUN_DLL G4ThreadLocalStatic T* offset; //Pointer to first instanc...
                                     ^
1 error generated.
scons: *** [build/macosx64/physics/PhysicsList.o] Error 1
-same thing is also occurred in rat-pac compile.

**Comment by hephys** [comment]
I think it might come from namespaces-related issues in OS X.
